### ISSUE TITLE
Not issue but question: how to hide panel

### ISSUE THREAD

**Issue by rossowl** [lovelylain/hass_ingress#10]
First of all, I would like to thank you for a great job.
I have a question if is possible to hide the panel from the left navigation without using the parent.
I have an ingress auth panel Vacuum cleaner that displays Valetudo in Roborock.
But I also have another lovelace panel Vacuum cleaner where are two tabs. The first tab is sensors e.g. ping, vacuum cleaner status, consumables status, buttons for quick cleaning the room etc. and the second is iframe with ingress Valetudo.
I would need to hide the ingress auth panel because it confuses my wife. She has two Vacuum cleaner panels underneath and often uses the button for quick cleaning on first tab in lovelace panel. She uses the Valetudo minimally, which is why it is only in the second tab.
Is there any way to solve this, for example by setting hide_panel: true or similar?
Thank you in advance for the answer.

**Comment by lovelylain** [comment]
why not use `parent` option? you can add an `iframe` `replace` panel link to any HA page, and use `parent` option put all other ingress panels under the link panel.
