### ISSUE TITLE
Ingress without sidebar?

### ISSUE THREAD

**Issue by rohankapoorcom** [lovelylain/hass_ingress#12]
Is it possible to load the ingressed page without drawing the sidebar? I'm trying to embed the ingressed app (Music Assistant) into an existing dashboard using the iframe card and it ends up with a second copy of the sidebar which doesn't look good.

![image](https://github.com/lovelylain/hass_ingress/assets/2511957/0e1909a3-4334-44ce-934a-b31cff6b3614)

**Comment by lovelylain** [comment]
Three methods:
- ui_mode: replace
  will always show ha loading page then replace ha window with ingressed page.
- add `?replace` param to panel url, `http://ha/panel_name?replace`.
  active replace ui_mode only when you need it.
- use `http://ha/api/ingress/panel_name` url.
  if token cookie is valid, show ingressed page. if not valid, jump to `http://ha/panel_name?replace` automaticly.

Recommend the last one.

**Comment by rohankapoorcom** [comment]
Thank you! This wasn't working with Home Assistant 2024.03.x, but I just upgraded to 2024.04.x and it's working now!

**Comment by lovelylain** [comment]
@rohankapoorcom Which of the above 3 methods did you choose?

**Comment by rohankapoorcom** [comment]
I used the third option (that way if I wanted to click on the item in the sidebar, it would still have the header). Now I just need to get the iframe card to handle resizing to fill the available space properly.

**Comment by bszczepanik** [comment]
@rohankapoorcom Could you share with your configuration? I have the same problem, but i can't solve this.

**Comment by rohankapoorcom** [comment]
Hi @bszczepanik 

I have this block in configuration.yaml:

```
ingress:
  musicassistant:
    work_mode: ingress
    ui_mode: toolbar
    url: http://localhost:8095
    title: Music Assistant
    icon: mdi:music
```

My lovelace card looks like this:

```
type: iframe
url: /api/ingress/musicassistant
```
