### ISSUE TITLE
Accessing simple local URL

### ISSUE THREAD

**Issue by pedroke** [lovelylain/hass_ingress#14]
Hi guys, thanks for the great plugin!
I would like to ask you for help, since I have a problem to understand which kind of local apps are supported.
When I try it e.g. with Node Red it is working simply by adding url: 192.168.0.x:1234
But I have e.g very basic static html with some js running on nginx, it is single index.html deployed  at 192.168.0.y:8500/test but this does not work.. but when I tried simply ngingx welcome message url: 192.168.0.y:8500, it is displayed fine..
also when I try e.g the admin interface of my router, e.g url: 192.168.0.1, it does not work neither...
So what the desired web app needs to fulfill to be embeddable? Somehow I don't get it..
Thanks a lot!

**Comment by lovelylain** [comment]
Notice: Not all backend services can be proxied by ingress, it must use relative paths or use X-Ingress-Path http header to generate correct absolute paths. For unsupported backend services, you can try `work_mode: auth` to work with another domain reverse proxied by nginx, or use nginx's sub_filter to fix the absolute paths in the response.

**Comment by pedroke** [comment]
Thanks a lot for hints, I will investigate further and try to adapt :)
