### ISSUE TITLE
weird offset when navigating on frigate beta

### ISSUE THREAD

**Issue by ivanjx** [lovelylain/hass_ingress#17]
when using frigate beta (0.14) and navigating to settings -> users (or other tabs) there is a weird offset that can only be fixed by rotating my iphone (ios 17.5.1). this behavior also observed with home assistant on safari. this behavior doesn’t happen in normal browser without hass ingress wrapping.

![IMG_3717](https://github.com/lovelylain/hass_ingress/assets/12814796/82ab3d79-e5c5-447c-a899-53b53f4389e9)

**Comment by lovelylain** [comment]
try `ui_mode: normal`?

**Comment by ivanjx** [comment]
same

![IMG_3719](https://github.com/lovelylain/hass_ingress/assets/12814796/bd63814f-cb00-4090-bd0b-6349a52f4712)

**Comment by lovelylain** [comment]
i cannot solve, if no problem with old version frigate, maybe you can report it to frigate.

**Comment by ivanjx** [comment]
@lovelylain i have been thinking to report it to the frigate repo but if i cant repro it using normal browser without hass_ingress they will just redirect me back here again

**Comment by ivanjx** [comment]
looks normal while accessing with safari (which should be the same engine used in home assistant app)

![IMG_3721](https://github.com/lovelylain/hass_ingress/assets/12814796/30b18a20-4899-47df-932c-f16509ee4d8e)

**Comment by lovelylain** [comment]
how about ha webpage dashboard? https://www.home-assistant.io/dashboards/dashboards/#webpage-dashboard

**Comment by ivanjx** [comment]
yes i can also reproduce it with the webpage card

![IMG_3722](https://github.com/lovelylain/hass_ingress/assets/12814796/97c9a68c-6241-4a01-8882-ce14f754794d)

**Comment by ivanjx** [comment]
i will redirect this issue to the home assistant frontend repo instead. thank you for your time.
