### ISSUE TITLE
Ingress tabs Looping back to main HA instance

### ISSUE THREAD

**Issue by hijamie32** [lovelylain/hass_ingress#3]
Hi,

Many thanks for the work on the integration.

I am having a strange issue. Node red that is running in a separate container works fine.

However anything else I try (other separate containers running on NAS or even router ip) either don't load and are blank, or loop back and show another copy of the main HA instance on the dashboard (window in window). This happens even with completely separate and non related ip's / ports.

I am using NPM for remote access but this happens with the addon enabled and disabled so don't think it is related.

Any idea I would be very grateful.

Many thanks.

Jamie
<img width="1368" alt="Screenshot 2024-03-11 at 18 58 15" src="https://github.com/lovelylain/hass_ingress/assets/24221940/91959125-a4ef-40da-a814-68ea98c26a03">
<img width="1374" alt="Screenshot 2024-03-11 at 18 58 01" src="https://github.com/lovelylain/hass_ingress/assets/24221940/d4b405a7-d272-416c-bb42-7efc658b37ab">

**Comment by lovelylain** [comment]
Show me your configuration pls.

**Comment by lovelylain** [comment]
ngix: is it ok to access http://192.168.1.42:81/ directly in the browser?
router: is it an openwrt? openwrt will reply a redirect if not login, you can use nginx's sub_filter fix it, https://github.com/lovelylain/hass_ingress/issues/1#issuecomment-1983617932

**Comment by hijamie32** [comment]
Hi, Yes direct in browser works fine for both.

Router is not openwrt, trying to ingress into a another instance of HA also just links back to the main instance even though they again are different IP's and ports:

title: HA
icon: mdi:home-assistant
toolbar: true
url: http://192.168.1.190:668

My main instance is 192.168.1.42:8123

Thanks again

**Comment by lovelylain** [comment]
ngix: you can view network log in browser F12 mode.
router: Not all backend services can be proxied by ingress, it must use relative paths or use X-Ingress-Path http header to generate correct absolute paths. For unsupported backend services, you can try to use nginx's sub_filter to fix the absolute paths in the response.

**Comment by hijamie32** [comment]
Would that be applicable to the remote HA instance as well?

Can't work out why it is just redirecting me back to the main HA instance....

**Comment by lovelylain** [comment]
For unsupported backend services, you can try `work_mode: auth` to work with another domain reverse proxied by nginx, or use nginx's sub_filter to fix the absolute paths in the response.
